Update faq-ajax.md
A minor correction on the example code of using Hooks part.
The setItems() function in the JSON fetch part should be "setItems(result.items);" instead of "setItems(result);"
Otherwise, it yields "TypeError: items.map is not a function"