Unify filename in React doc and gist
In this page: https://gist.github.com/gaearon/42a2ffa41b8319948f9be4076286e1f3
filename is like_button.js.
But actual filename in React Doc Beta is like-button.js.
This difference caused the command to fail.

```
$ npx terser -c -m -o like_button.min.js -- like_button.js
ERROR: ENOENT: no such file or directory, open 'like_button.js'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at read_file (/Users/keiko/playground/hello-react/node_modules/terser/dist/bundle.min.js:30065:23)
    at /Users/keiko/playground/hello-react/node_modules/terser/dist/bundle.min.js:29872:41
    at Array.forEach (<anonymous>)
    at run_cli (/Users/keiko/playground/hello-react/node_modules/terser/dist/bundle.min.js:29871:32)
```